# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('plaid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plaid_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('plaid_public_token', models.CharField(blank=True, max_length=255, null=True)),
                ('finicity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_only', models.BooleanField(default=True)),
                ('reauth_required', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/institution/logo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('finicity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plaid_id', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(default='#000000', max_length=21)),
                ('image', models.ImageField(blank=True, null=True, upload_to='finicity/institutions')),
                ('default', models.CharField(blank=True, choices=[('', 'Search Only'), ('us', 'USA'), ('ca', 'Canada')], default='', max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set([('plaid_id', 'owner')]),
        ),
    ]
