# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_auto_20160607_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='upload_only',
            field=models.BooleanField(default=True),
        ),
    ]
