# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-23 22:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buckets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buckets.Bucket')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeFromSavings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('month_start', models.DateTimeField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_from_savings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('raw_description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(db_index=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plaid_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('finicity_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('from_savings', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('plaid', 'Plaid'), ('finicity', 'Finicity'), ('demo', 'Demo Data')], max_length=255)),
                ('_transfer_pair', models.ManyToManyField(related_name='_transaction__transfer_pair_+', to='transactions.Transaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account')),
                ('buckets', models.ManyToManyField(related_name='transactions', through='transactions.BucketTransaction', to='buckets.Bucket')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='buckettransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='buckettransaction',
            unique_together=set([('bucket', 'transaction')]),
        ),
    ]
